In [6]:
import numpy as np
import tensorflow
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [7]:
td=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
train_data=td.flow_from_directory('dataset/training_set',batch_size=32,target_size=(64,64,),class_mode='binary')

Found 8000 images belonging to 2 classes.


In [8]:
ts=ImageDataGenerator(rescale=1./255)
test_data=td.flow_from_directory('dataset/test_set',batch_size=32,class_mode='binary',target_size=(64,64))

Found 1992 images belonging to 2 classes.


In [9]:
from tensorflow.keras.layers import Conv2D,MaxPool2D,Flatten,Dense
from tensorflow.keras.models import Sequential
model=Sequential()
model.add(Conv2D(filters=32,kernel_size=3,input_shape=[64,64,3],activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2,padding='same'))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2,padding='same'))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [10]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(train_data,validation_data=test_data,epochs=25)

C:\Users\k.navadeepreddy\anaconda3\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


Epoch 1/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 32s 123ms/step - accuracy: 0.5581 - loss: 0.6810 - val_accuracy: 0.6586 - val_loss: 0.6263
Epoch 2/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 29s 115ms/step - accuracy: 0.6684 - loss: 0.6076 - val_accuracy: 0.6486 - val_loss: 0.6328
Epoch 3/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 29s 117ms/step - accuracy: 0.7142 - loss: 0.5613 - val_accuracy: 0.7339 - val_loss: 0.5336
Epoch 4/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 30s 122ms/step - accuracy: 0.7385 - loss: 0.5179 - val_accuracy: 0.7385 - val_loss: 0.5400
Epoch 5/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 31s 125ms/step - accuracy: 0.7679 - loss: 0.4829 - val_accuracy: 0.7470 - val_loss: 0.5176
Epoch 6/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 29s 117ms/step - accuracy: 0.7595 - loss: 0.4839 - val_accuracy: 0.7776 - val_loss: 0.4844
Epoch 7/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 30s 118ms/step - accuracy: 0.7847 - loss: 0.4546 - val_accuracy: 0.7746 - val_loss: 0.4736
Epoch 8/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 30s 120ms/step - accuracy: 0.7949 - loss: 0

In [11]:
import os
from tensorflow.keras.preprocessing import image
images='dataset/single_prediction'
images_path=[os.path.join(images,fname) for fname in os.listdir(images)]
img=[]
for imgs in images_path:
    test_data_set=image.load_img(imgs,target_size=(64,64))
    test_data_set=image.img_to_array(test_data_set)
    test_data_set=np.expand_dims(test_data_set,axis=0)
    img.append(test_data_set)
pre=np.vstack(img)
pred=model.predict(pre)
for i,res in enumerate(pred):
    pre_label='Dog' if res[0]>0.5 else 'Cat'
    print(f"Image{i+1}:{pre_label}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
Image1:Dog
Image2:Cat
Image3:Dog
Image4:Dog
Image5:Dog
Image6:Dog
Image7:Dog
Image8:Cat
Image9:Dog
Image10:Dog


In [12]:
for i,res in enumerate(pred):
    pre_label='Dog' if res[0]>0.5 else 'Cat'
    print(f"Image{i+1}:{pre}")

Image1:[[[[124. 119. 100.]
   [122. 116. 100.]
   [124. 118. 106.]
   ...
   [102.  42.  16.]
   [113.  39.  10.]
   [103.  39.  12.]]

  [[121. 116.  97.]
   [135. 129. 113.]
   [128. 122. 110.]
   ...
   [113.  41.  16.]
   [103.  38.  10.]
   [118.  56.  31.]]

  [[127. 122. 103.]
   [134. 129. 110.]
   [139. 134. 115.]
   ...
   [119.  52.  23.]
   [116.  49.  20.]
   [115.  45.  19.]]

  ...

  [[ 84.  81.  50.]
   [ 91.  87.  62.]
   [ 87.  84.  51.]
   ...
   [100.  43.  16.]
   [ 93.  38.  17.]
   [100.  42.  20.]]

  [[ 79.  78.  47.]
   [ 84.  82.  57.]
   [ 83.  83.  49.]
   ...
   [ 99.  43.  18.]
   [ 92.  41.  14.]
   [100.  43.  24.]]

  [[ 83.  82.  51.]
   [ 83.  81.  56.]
   [ 83.  83.  49.]
   ...
   [ 99.  44.  14.]
   [ 93.  42.  11.]
   [ 95.  44.  13.]]]


 [[[  4.   0.   0.]
   [ 13.  29.  44.]
   [  4.   2.   3.]
   ...
   [ 14.  24.  26.]
   [ 19.  28.  35.]
   [  0.  12.  18.]]

  [[  5.   1.   0.]
   [ 15.  31.  46.]
   [  3.   1.   4.]
   ...
   [ 19.  29. 